{
  parserClass="com.hoho.coocoo.parser.CoocooParser"
  stubParserClass="com.hoho.coocoo.parser.GeneratedParserUtilBase"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Coocoo"
  psiImplClassSuffix="Impl"
  psiPackage="com.hoho.coocoo.psi"
  psiImplPackage="com.hoho.coocoo.psi.impl"

  elementTypeHolderClass="com.hoho.coocoo.psi.CoocooTypes"
  elementTypeClass="com.hoho.coocoo.psi.CoocooElementType"
  tokenTypeClass="com.hoho.coocoo.psi.CoocooTokenType"
}

private elements ::= KEYWORD VARIABLE COOCLASS COONAME COMMENT IDENTIFIER STRING JAVASCRIPT_BEGIN JAVASCRIPT JAVASCRIPT_END SUBCOOCOO PUSHER CRLF WHITE_SPACE VARIABLE_GETTER PROPERTY_GETTER TYPIFICATION NULLABLE

root ::= elements
